# LI PROGRAMA DE VERÃO (2022 - edição 51)


<img src='../figuras/paisagem.png'>

## Recapitulando a aula anterior:




<img src='../figuras/revisao.jpeg'>


> * int, str, float, bool
> * listas, tuplas, dicionários, conjuntos
> * como construir funções

# Bibliotecas

* Pandas *
* Numpy *
* MatplotLib
* Sklearn

# Numpy 

* Biblioteca para cálculos númericos multidimensionais 
* Os Arrays NumPy são usados para armazenar os dados de treinamento, bem como os parâmetros dos modelos de Machine Learning.
* O tipo principal, o ndarray é um bloco de mémoria continuo com itens do mesmo tipo

* ndarray : é um array multidimensional rápico e eficiente no consumo de memória, provendo operações aritméticas e outros recursos sofisticados; 
* funções matemáticas padronizadas para operações rápidas sem necessidade de loops
* ferramentas para leitura e escrita em disco 
* algebra linear, geração de numéros randômicos e transformada de fourie;
* integração com C e Fortran

## O que vamos aprender sobre o numpy? 

* como criar?
* atributos: size, shape, data type
* como adicionar, remover e ordenar elementos?
* como acessar? 
* operações úteis 
* como salvar e ler um arquivo 

### Import

In [1]:
import numpy as np # pq usar o np ao invés de apenas numpy?

### Create 

* array
* ones, empty, zeros
* identity, eye

**Unidimensional**
 (possuem apenas uma dimensão)

In [2]:
a = np.array([1,2,3,4,5]) # criando array a

In [3]:
a

array([1, 2, 3, 4, 5])

* Mas qual a diferença do array numpy e as listas que vimos na aula anterior? 

Na maior parte das vezes, o Numpy é mais rápido e consome menos memória

In [4]:
a = np.array([1,'2',3,4,5]) # criar um np array com tipos mistos; o que vai acontecer aqui?
a

array(['1', '2', '3', '4', '5'], dtype='<U21')

E como fazer o cast de tuplas e sets para np.arrays?

In [5]:
tuplas = (1,2,3)# criando a partir de uma tupla 
np.array(tuplas)

array([1, 2, 3])

In [7]:
conjunto = {1,2,3,3} # criando a partir de um set
np.array(conjunto)

array({1, 2, 3}, dtype=object)

Outra coisa interessante é que podemos definir o tipo dos itens do array

In [14]:
a = np.array([1,2,3,4], dtype = 'float64' ) # especificando o tipo float
print(a)

b = np.array([1,2,3,4], dtype = 'int64' )  # especificando o tipo int
print(b)
c = np.array([12,22,30,40], dtype = 'string_' )  # especificando o tipo str
print(c)

[1. 2. 3. 4.]
[1 2 3 4]
[b'12' b'22' b'30' b'40']


Vamos verificar os tipos: 

In [15]:
c.dtype # usando dtype

dtype('S2')

In [17]:
lista = [12,12,4]

In [18]:
type(lista)

list

In [16]:
type(c) # veja que isso é diferente de dtype

numpy.ndarray

E podemos alterar o tipo depois do array prnto? 

In [24]:
a = np.array([5,6,7]) # criando um array
a.dtype# verificar o tipo 
a.astype('float64').dtype # alterar o tipo usando astype
# verificar o novo tipo

dtype('float64')

In [26]:
a = np.array([5.0, 4.5])# criando um array de floats
a.dtype# verificando o dtype
a.astype('int64').dtype# alterando pra int usando astype

dtype('int64')

In [29]:
a = a.astype('int64')
a

array([5, 4])

In [37]:
numeros_strings = np.array(['1.2', '1.5']) # criando um array de strings


In [38]:
numeros_strings

array(['1.2', '1.5'], dtype='<U3')

In [39]:
numeros_strings.astype('float64')# transformando em float

array([1.2, 1.5])

**Ndimensional**

<img src='../figuras/n_dim.png'>

In [41]:
arr2D = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])   # criando um narray de 3 linhas e 4 colunas
arr2D

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Cada array tem os seguintes atributos: 

* ndim (numero de dimensões)
* shape ( tamanho de cada dimensão)
* size ( tamanho total do array)


In [42]:
 arr2D.ndim # ndim

2

In [43]:
arr2D.shape# shape

(3, 4)

In [44]:
arr2D.size #size

12

In [45]:
arr2D.nbytes # tm podemos verificar o quanto de memória esta sendo consumida usando nbytes

96

In [46]:
a_string = np.array(['1', '2', '3', '4'])
a_string.nbytes

16

**Casos especiais de criação**

In [48]:
np.zeros(10) # array de zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [50]:
np.zeros((2, 1))# narray

array([[0.],
       [0.]])

In [55]:
z = np.ones((2,10)) #array de uns
z.ndim
z.shape

(2, 10)

In [56]:
np.empty(2) # array vazio >>> vcs sabem que valores são esses? pq não são zeros?

array([5. , 4.5])

In [63]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [62]:
np.arange(0,10)# gerando valores sequenciais com arange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
np.arange(0,10,2) # gerando valores com step

array([0, 2, 4, 6, 8])

In [65]:
np.linspace(0,10,5) # espaçados linearmente - linspace

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [66]:
np.ones(10, dtype='int32')# especificando o tipo em np ones


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [67]:
np.ones(10, dtype='string_')# especificando o tipo em np ones


array([b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1'],
      dtype='|S1')

* **Shape**

In [73]:
array_example = np.array([ [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 1, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]] ])

array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 1, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [74]:
array_example.ndim

3

In [75]:
array_example.size

24

In [76]:
array_example.shape

(3, 2, 4)

* Reshape 

In [79]:
a = np.arange(6) 
a.ndim

1

In [82]:
reshape_a = a.reshape(3,2) # fazer o reshape para (3,2)
reshape_a.shape

(3, 2)

In [85]:
np.reshape(a, newshape=(1, 6), order='C') # order language like index order

array([[0, 1, 2, 3, 4, 5]])

In [86]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [88]:
a.ndim

1

In [92]:
novo_eixo = a[:, np.newaxis] # add um novo eixo com np.newaxis
novo_eixo

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [94]:
novo_eixo.shape

(6, 1)

In [95]:
a[np.newaxis, :] # row_vecotr a[np.newaxis, :]


array([[1, 2, 3, 4, 5, 6]])

In [99]:
a

array([1, 2, 3, 4, 5, 6])

In [100]:
a[:, None]


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [101]:
c = np.array([[1, 2, 3], [4, 5, 6]]) # ndarray
c.shape

(2, 3)

In [102]:
c # vendo conteudo do vetor

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
c[:, np.newaxis] # teste com um ndarray

array([[[1, 2, 3]],

       [[4, 5, 6]]])

**Indexing e slicing**

In [105]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [106]:
a[0] # similar as series ou listas []


1

In [107]:
a[0:2]# intervalos definidos

array([1, 2])

In [108]:
a[1:] # intervalos [1:]

array([2, 3, 4, 5, 6])

In [110]:
a

array([1, 2, 3, 4, 5, 6])

In [112]:
a[-1:] # final usando [-1:]

array([6])

In [113]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # criando um vetor ndarray
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

<img src='../figuras/indexing_numpy.png'>

In [115]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [116]:
arr2d[1]  # acessando uma dimensao 

array([4, 5, 6])

In [117]:
arr2d[0][0] # acessando um valor de uma dimensao com [][]

1

In [118]:
arr2d[0,0] # acessando um valor de uma dimensao com [,]

1

In [119]:
arr2d[0,0] = -1

In [120]:
arr2d

array([[-1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

* cuidado com as alterações!!!

façam cópias

**slicing condicional**

In [123]:
a3 = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [129]:
a3[a3 >= 5] # a[a<5]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [131]:
five_up = (a3>5) # (a > 5)

In [132]:
a3[five_up] # selecionar os valores que sao true no five_up de cima

array([ 6,  7,  8,  9, 10, 11, 12])

In [133]:
divisible_by_2 = a3[a3%2==0]  # usando mod
divisible_by_2

array([ 2,  4,  6,  8, 10, 12])

In [136]:
a3[(a3 > 2) & (a3 < 8)]  # usando mais de uma condição com & para retornar a lista
 

array([3, 4, 5, 6, 7])

In [137]:
a3[(a3 > 2) | (a3 < 8)] # usando mais de uma condição com | para retornar true e false 



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [139]:
x = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]]) 
x

array([[3, 0, 0],
       [0, 4, 0],
       [5, 6, 0]])

In [140]:
# verificar quais campos sao zero
np.nonzero(x)

(array([0, 1, 2, 2]), array([0, 1, 0, 1]))

In [141]:
a = np.array([[1, 2, 3, 4], [5, 1, 7, 8], [9, 10, 11, 12]])

In [142]:
np.nonzero(x <5) # verificar se tem algum valor igual a 0  com uma condicional


(array([0, 0, 0, 1, 1, 1, 2]), array([0, 1, 2, 0, 1, 2, 2]))

In [148]:
b = np.array([[1,2],[4,6]])
b


array([[1, 2],
       [4, 6]])

In [153]:
list(zip(b[1], b[0]))

[(4, 1), (6, 2)]

In [164]:
b[0]

array([1, 2])

In [165]:
b[1]

array([4, 6])

In [166]:
list(zip(b[0], b[1]))

[(1, 4), (2, 6)]

In [149]:
list(zip(b[0], b[1])) # coordenadas

[(1, 4), (2, 6)]

In [154]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(1, 4)
(2, 6)


In [172]:
a = ("John", "Charles", "Mike")
b = ("Jenny", "Christy", "Monica", "Vicky")




In [175]:
tuple(zip(b,a))

(('Jenny', 'John'), ('Christy', 'Charles'), ('Monica', 'Mike'))

In [156]:
# print(a[b])

In [157]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [158]:
nomes = np.array(['Wal', 'Paula', 'Edna', 'Alberto'])

In [161]:
nomes[nomes != 'Wal']

array(['Paula', 'Edna', 'Alberto'], dtype='<U7')

**Adicionar, remover, e ordenar**

In [176]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8]) # criando um array
arr 

array([2, 1, 5, 3, 7, 4, 6, 8])

* adicionar na mesma posição que já existe um valor -- modificar um valor

In [179]:
arr[0] = -1 # modificar uma posicao


In [180]:
arr

array([-1,  1,  5,  3,  7,  4,  6,  8])

* adicionar sem substituir

In [188]:
np.insert(arr, 2, 50)

array([-1,  1, 50,  5,  3,  7,  4,  6,  8])

* remover 

In [189]:
np.delete(arr, 0, -1) # numpy.delete(arr, obj, axis=None)

array([1, 5, 3, 7, 4, 6, 8])

* ordenar 

In [191]:
np.sort(arr) # usar o sort

array([-1,  1,  3,  4,  5,  6,  7,  8])

In [194]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

* concatenar 

In [207]:
np.concatenate((a,b), axis=0) # concatenate

array([1, 2, 3, 4, 5, 6, 7, 8])

In [208]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [2,3]])

In [209]:
x

array([[1, 2],
       [3, 4]])

In [210]:
y

array([[5, 6],
       [2, 3]])

In [213]:
np.concatenate((x,y), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 2, 3]])

**vstack e hstack**

Tipos de concatenação: vertical e horizontal

In [214]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [216]:
np.vstack((a1,a2)) # usar o vstack

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [217]:
np.hstack((a1,a2)) # usar o hstack

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [218]:
x = np.arange(1, 25).reshape(2, 12)

In [219]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [221]:
z = np.hsplit(x, 3) # hsplit (arr, size)

### Operações

In [229]:
numpy_ser = np.array([20,60,60,10,15])

In [230]:
np.mean(numpy_ser) # media

33.0

In [231]:
np.median(numpy_ser)

20.0

In [233]:
numpy_ser[numpy_ser >= np.median(numpy_ser)] # function median 

array([20, 60, 60])

In [234]:
lista = [1, 3, 4] * 2 # multiplicação de uma lista por um scalar
lista

[1, 3, 4, 1, 3, 4]

In [235]:
[x*2 for x in [1, 3, 4]] # mmultiplicacao 

[2, 6, 8]

In [236]:
data = np.array([1, 3,4]) 
data * 2 # operações em batch 

array([2, 6, 8])

In [237]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [238]:
arr*arr # operações em batch

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [239]:
arr - arr # operações em batch

array([[0., 0., 0.],
       [0., 0., 0.]])

In [241]:
1 / arr # operações em batch

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [242]:
0.5* arr # operações em batch

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [244]:
data = np.array([1, 2])
data


array([1, 2])

In [246]:
ones = np.ones(2, dtype=int)
ones

array([1, 1])

In [247]:
data + ones # operações em batch

array([2, 3])

In [248]:
data.max() # max
data.min() # min
data.mean() # mean

1.5

In [250]:
data.max()

2

In [249]:
np.max(data)

2

In [251]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
np.unique(a) # distintos

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [252]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count) # contagem dos itens

[3 2 2 2 1 1 1 1 1 1]


In [253]:
unique_values

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
# intersect? union?

In [254]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reversed_arr = np.flip(arr) # reverso
reversed_arr

array([8, 7, 6, 5, 4, 3, 2, 1])

**Funções Universais**

Funções que aplicam a operação elemento a elemento

In [255]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [256]:
np.sqrt(arr) # sqrt

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [257]:
np.exp(arr) #exp

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

**Funções unárias**

recebem dois arrays e retornam um array

In [258]:
from numpy.random import randn
x = randn(8)
y = randn(8)

In [259]:
x

array([-1.66269875,  0.72559193, -0.23261927, -0.29040079, -1.10976352,
        0.59989321,  0.17695241, -0.34699175])

In [260]:
np.maximum(x, y) # maximum

array([ 0.89550988,  0.72559193, -0.1787439 ,  0.43766777,  0.61271665,
        0.63317411,  0.17695241, -0.34699175])

In [261]:
arr = randn(7) * 5

In [262]:
arr

array([-0.02897127,  0.08397663, -4.59867069,  0.53048042, -4.48727246,
        9.62561208,  6.01577498])

In [263]:
np.modf(arr) # #mod

(array([-0.02897127,  0.08397663, -0.59867069,  0.53048042, -0.48727246,
         0.62561208,  0.01577498]),
 array([-0.,  0., -4.,  0., -4.,  9.,  6.]))

### Salvar e ler 

In [265]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [266]:
np.save('some_array', arr) # save

In [267]:
np.load('some_array.npy') #load

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [268]:
arr = np.loadtxt('../notebooks/array.txt', delimiter=',') #sloadtxt e savetxt
arr

array([[ 0.580052,  0.18673 ,  1.040717,  1.134411],
       [ 0.194163, -0.636917, -0.938659,  0.124094],
       [-0.12641 ,  0.268607, -0.695724,  0.047428],
       [-1.484413,  0.004176, -0.744203,  0.005487],
       [ 2.302869,  0.200131,  1.670238, -1.88109 ],
       [-0.19323 ,  1.047233,  0.482803,  0.960334]])

# Referencias 

* devmedia.com.br

* https://jovemnerd.com.br/nerdcast/nerdtech/vingadores-do-data-science/

* https://www.youtube.com/watch?v=5b9Z8toVaAU

* https://www.devmedia.com.br/tipos-de-dados-em-python-string/40669

* https://gvanrossum.github.io/

* https://numpy.org/learn/