## Nome: Flávio Bezerra Pereira

In [129]:
import numpy as np

### 1. Considere as seguintes matrizes:

In [130]:
A= np.array([[2,3,4],[1,2,4]])
A

array([[2, 3, 4],
       [1, 2, 4]])

In [131]:
B= np.array([[7,3],[0,3],[10,0]])
B

array([[ 7,  3],
       [ 0,  3],
       [10,  0]])

### Verifique se é possivel a multiplicação de A*B, caso seja, multiplique e depois concatenate por coluna a primeira linha de A com a segunda coluna de B.

In [133]:
dimensao_A = A.ndim
numero_linha_A = A.shape[0]
numero_coluna_A = A.shape[1]
dimensao_B = B.ndim
numero_linha_B = B.shape[0]
numero_coluna_B = B.shape[1]
if ((dimensao_A == dimensao_B) and (numero_linha_A == numero_coluna_B) and (numero_coluna_A == numero_linha_B)):
    print("Possível a multiplicação")

Possível a multiplicação


In [134]:
print(A.dot(B)) # multiplicacao A*B
A[0,].reshape(-1,1) # primeira linha de A em formato de coluna
B[:,[1]].shape # segunda coluna de B
np.hstack((A[0,].reshape(-1,1), B[:,[1]])) # concatenacao por coluna da primeira linha de A com a segunda coluna de B

[[54 15]
 [47  9]]


array([[2, 3],
       [3, 3],
       [4, 0]])

### 2. Acesse os elementos comuns entre a e b usando numpy

In [136]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [137]:
np.intersect1d(a, b)

array([2, 4])

### 3. Mostre as posições onde os dois vetores são iguais usando numpy

In [79]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [138]:
np.where(np.equal(a, b)) # exibe as posicoes onde os valores sao iguais

(array([1, 3, 5, 7]),)

### 4. Transforme os seguintes objetos em np.array:

In [140]:
a=[[1,2], [4, 5]]
a

[[1, 2], [4, 5]]

In [141]:
b=(1,2,4,8)
b

(1, 2, 4, 8)

In [142]:
c={1,2,6}
c

{1, 2, 6}

In [143]:
print(np.array(a))
print(np.array(b))
print(np.array(list(c))) # converte o set em uma lista depois converte para numpy array

[[1 2]
 [4 5]]
[1 2 4 8]
[1 2 6]


### 5. Considere o seguinte vetor:

In [144]:
x=np.array([[7,3],[0,3],[10,0]])
x

array([[ 7,  3],
       [ 0,  3],
       [10,  0]])

- Acesse o elemento da segunda linha e primeira coluna
- Acesse a segunda coluna
- Acesse as duas últimas linhas das duas colunas
- Acesse o elemento da terceira linha e segunda coluna

In [145]:
x[1,0]

0

In [146]:
x[:,[1]]

array([[3],
       [3],
       [0]])

In [147]:
x[1:3,]

array([[ 0,  3],
       [10,  0]])

In [148]:
x[2,1]

0

## Exercícios para casa

### 6. Selecione as duas primeiras colunas de A, em seguida, calcule o determinante de A, caso seja invertível, calcule sua matriz inversa.

In [149]:
A= np.array([[2,3,4],[1,2,4]])
A

array([[2, 3, 4],
       [1, 2, 4]])

In [150]:
colunas_A = A[:,[0, 1]] # duas primeiras colunas de A
print(colunas_A)

[[2 3]
 [1 2]]


In [151]:
np.linalg.det(colunas_A) # determinante das duas primeiras colunas de A

1.0

In [152]:
np.linalg.inv(colunas_A) # inversa das duas primeiras colunas de A

array([[ 2., -3.],
       [-1.,  2.]])

### 7.  Considere a seguinte matriz:

In [153]:
x=np.random.normal(0, 1, (3,3))
x

array([[ 0.55066905,  1.30165872,  1.087437  ],
       [ 0.04047907,  1.02135399,  0.32951698],
       [ 0.30855108, -2.22390698, -0.22414879]])

#### Crie um vetor para cada situação a seguir:
1. Com os elementos maiores que a média.
2. Com os elementos menores que a mediana
3. Com os elementos positivos

In [154]:
print(np.mean(x))
x[x > np.mean(x)]

0.24351223502578614


array([0.55066905, 1.30165872, 1.087437  , 1.02135399, 0.32951698,
       0.30855108])

In [155]:
print(np.median(x))
x[x < np.median(x)]

0.3295169758970996


array([ 0.04047907,  0.30855108, -2.22390698, -0.22414879])

In [156]:
x[x > 0]

array([0.55066905, 1.30165872, 1.087437  , 0.04047907, 1.02135399,
       0.32951698, 0.30855108])

### 8. Selecione o valor mais frequente do seguinte vetor

In [157]:
x=np.array([2,2,3,5,2,8])
x

array([2, 2, 3, 5, 2, 8])

In [158]:
counts = np.bincount(x) # contagem de ocorrencia dos elementos inteiros de um vetor
print (counts) # posicao 2 contagem 3 significa que o numero 2 apareceu 3 vezes no vetor x

[0 0 3 1 0 1 0 0 1]


In [159]:
print(np.argmax(counts)) # retornar o indice com maior contagem de ocorrencia, significa que o 2 e o valor mais frequente

2
